# Generated by Django 5.0.1 on 2024-01-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=1000)),
                ('short_url', models.CharField(max_length=100)),
                ('date_time_created', models.DateTimeField()),
            ],
        ),
    ]
